name: Run npm test

on:
  push:
    branches:
      - main # Replace 'main' with your default branch if different
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Specify the Node.js version you want

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
